from django.urls import path,re_path,include
from . import views
from django.contrib.auth import views as auth_views
# url(r'^blog/(?P<blog_id>\d+)/$'
urlpatterns = [
    # path('',views.index,name='index'),
    # path('<gender>/', views.index, name='first1'),
    # path('add/', views.add, name='add_members'),
    # path('add/add_record/', views.add_record, name='add_record'),
    # path('delete/<int:id>',views.delete,name='delete'),
    # path('test1/', views.test1, name='test'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.register_User, name='register'),    
    path('profile/<str:pk>', views.profile, name='profile'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('add_product/',views.add_product,name='add_product'),
    path('shopping_cart/',views.shopping_carts,name='shopping_cart'),
    path('delete_product/<int:pk>',views.delete_product,name='delete_product'),
    path('add_product2/',views.add_product2,name='add_product2'),
    path('',views.home,name='home'),
    path('login1/',views.login1,name='login1'),
    path('member_centre/',views.member_center,name='member_centre'),
    path('member_profile/',views.member_profile,name='member_profile'),
    path('product/<str:pk>', views.product_page, name='product'),
    path('buy/',views.buy,name='buy'),
    path('category/<str:pk>/',views.category,name='category'),
    path('purchase_record/',views.purchase_record,name='purchase_record'),
    path('tracking_list/',views.tracking_list_page,name='tracking_list'),
    path('add_tl/',views.add_tl,name='add_tl'),
    path('delete_tl/<int:pk>',views.delete_tl,name='delete_tl'),
    # path('a/',views.a,name='a'),
    path('check_out/',views.check_out,name='check_out'),
    path('save_order/',views.save_order,name='save_order'),
    path('delete_check/<int:pk>',views.delete_check,name='delete_check'),
    path('admin_order_tracking/',views.admin_order_tracking,name='admin_order_tracking'),
    path('detail/<int:pk>',views.admin_order_tracking_detail,name='detail'),
    path('update_state/',views.update_state,name='update_state'),
    path('user_order_tracking/',views.user_order_tracking,name='user_order_tracking'),
    path('search/',views.search,name='search'),
    path('send_email/',views.send_email_,name='send_email'),
    path('cpu_rank/',views.cpu_rank,name='cpu_rank'),
    path('cp/',views.cp),
    path('gpu_rank/',views.gpu_rank,name='gpu_rank'),
    path('Line_robot/',views.Line_robot,name='Line_robot'),
    path('social-auth/',include('social_django.urls',namespace='social')),
    path('accounts/', include('allauth.urls')),
    # path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('change-password/', views.change_password, name='change_password'),
]