"""
Django settings for mytestsite project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
from dotenv import load_dotenv # 2. 匯入 load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
 }
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'catalog.apps.CatalogConfig', 
    'model',
    'crispy_forms',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # 'social_django',
]
SITE_ID = 1


# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
# EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_mail")
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# CRISPY_TEMPLATE_PACK = 'uni_form'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'stmail.nptu.edu.tw'  #SMTP伺服器
# EMAIL_PORT = 25  #TLS通訊埠號
# EMAIL_USE_TLS = True  #開啟TLS(傳輸層安全性)
# EMAIL_HOST_USER = 'cbf108022@stmail.nptu.edu.tw'  #寄件者電子郵件
# EMAIL_HOST_PASSWORD = 'Nptu45137890'  #密碼

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
CRISPY_TEMPLATE_PACK = 'uni_form'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  #SMTP伺服器
EMAIL_PORT = 587  #TLS通訊埠號
EMAIL_USE_TLS = True  #開啟TLS(傳輸層安全性)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')  #寄件者電子郵件
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')  #密碼

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'social_django.middleware.SocialAuthExceptionMiddleware',
    # 'social_django.context_processors.backends'
    
]

ROOT_URLCONF = 'mytestsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"view")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
                'my_tags':'model.templates.my_tags',
            }
        },
    },
]
# AUTH_USER_MODEL = 'model.client_user'

WSGI_APPLICATION = 'mytestsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', #因為你用的是MySQL
        'NAME': 'data',                       
        'USER': 'root',                       #這裡用最高權限管理員
        'PASSWORD': 'Aw1234',            #你的密碼
        'HOST': '',                           #空白預設為localhost
        'PORT': '',         
    }
}'''

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DATABASE_ENGINE'),
        'NAME': os.environ.get('DATABASE_NAME'),     # 您建立 Docker 時設定的 POSTGRES_DB
        'USER': os.environ.get('DATABASE_USER'),      # 您建立 Docker 時設定的 POSTGRES_USER (通常是 'postgres')
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),  # 您建立 Docker 時設定的 POSTGRES_PASSWORD
        'HOST': os.environ.get('DATABASE_HOST'),             # 或是 '127.0.0.1'
        'PORT': os.environ.get('DATABASE_PORT'),                  # 這是 PostgreSQL 的預設埠號
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,"statics")
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/'  # 登入後的首頁網址
# AUTHENTICATION_BACKENDS=[
#     'social_core.backends.google.GoogleOAuth2',
#     'django.contrib.auth.backends.ModelBackend'
# ]
# LOGIN_URL='login'
# LOGIN_REDIRECT_URL='login'
# LOGOUT_URL='logout'
# LOGOUT_REDIRECT_RUL='login'
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=os.environ.get('GOOGLE_CLIENT_ID')
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=os.environ.get('GOOGLE_CLIENT_SECRET')