# Generated by Django 4.0.6 on 2022-09-22 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0014_purchase_record_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracking_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_product_nameOf', to='model.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tl_usernameOf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
