# Generated by Django 4.0.6 on 2022-10-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_user',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
