# Generated by Django 4.0.6 on 2022-10-02 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0017_alter_client_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default='')),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='od_product_nameOf', to='model.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_usernameOf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
