# Generated by Django 4.0.6 on 2022-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='piker',
            field=models.CharField(default='', max_length=100),
        ),
    ]
