# Generated by Django 4.0.6 on 2022-10-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0019_order_piker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default='', max_length=10),
        ),
    ]
