# Generated by Django 4.0.6 on 2022-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0020_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
