# Generated by Django 4.0.6 on 2022-10-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0021_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
