# Generated by Django 4.0.6 on 2022-10-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0022_order_counts_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_file',
            field=models.CharField(default='', max_length=100),
        ),
    ]
