# Generated by Django 4.0.6 on 2022-10-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model', '0023_product_img_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='checks',
            field=models.CharField(default='', max_length=10),
        ),
    ]
