# Generated by Django 4.0.6 on 2022-10-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    table_name = "model_product"
    field_name = "product_name"
    index_name = f"{table_name}_{field_name}_index"
    dependencies = [
        ('model', '0024_shopping_cart_checks'),
    ]

    '''operations = [
        migrations.RunSQL(
            f"CREATE FULLTEXT INDEX {index_name} ON {table_name} ({field_name})",
            f"DROP INDEX {index_name} ON {table_name}",
        ),
    ]'''
    operations = [
        migrations.RunSQL(
            # 1. 這是 PostgreSQL 的 "CREATE INDEX" 語法 (Forward)
            # 我們使用 GIN 索引 和 to_tsvector 函數
            f"CREATE INDEX {index_name} ON {table_name} USING GIN (to_tsvector('simple', {field_name}))",
            
            # 2. 這是 PostgreSQL 的 "DROP INDEX" 語法 (Backward)
            f"DROP INDEX IF EXISTS {index_name}",
        ),
    ]
