# Generated by Django 4.0.6 on 2022-11-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0025_add_fulltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
