# Generated by Django 4.0.6 on 2022-12-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0027_alter_order_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_file',
            new_name='search_label',
        ),
    ]
